### ISSUE TITLE
Dbus errors and exceptions.

### ISSUE THREAD

**Issue by maotora** [Toobkrow/mountie#1]
Hello, I'm using ArchLinux and python3 to run your project and i'm getting this error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maotora/mountie/mountie.py", line 146, in <module>
    proxy = system_bus.get_object('org.freedesktop.UDisks', '/org/freedesktop/UDisks')
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files
```

**Comment by Toobkrow** [comment]
Hi, I wrote this script several years ago and don't use or maintain it any more, and the calls to dbus and udisks are probably outdated.
I won't fix this error.
If you are interested in submitting a patch I can add you to the repository.
Best Regards
